"""first version

Revision ID: a80573f43822
Revises: 885a287e90e3
Create Date: 2025-12-08 02:48:42.367783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a80573f43822'
down_revision: Union[str, None] = '885a287e90e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_file', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('model', sa.Column('documentation_markdown', sa.Text(), nullable=True))
    op.alter_column('model', 'git_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'git_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('model', 'documentation_markdown')
    op.alter_column('base_file', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
